const endpoints = {
	LOGIN: "/login",
	REGISTER: "/register",
	SEND_OTP: "/send-otp",
	VERIFY_OTP_CHANGE_PASSWORD: "/verify-otp-and-change-password",
<<<<<<< HEAD
	GET_INFOR_USER: "/get-infor",
	CREATE_APPOINTMENT: "/create-appointment",
	APPROVE_APPOINTMENT: "/approve/:appointmentId",
	REJECT_APPOINTMENT: "/reject/:appointmentId",
	CREATE_FEEDBACK: "/create-feedback",
	ADD_FAVORITE_STYLIST: "/add-favorite-stylist",
	RECOMMENDED_STYLIST: "/recommended-stylists",
	CREATE_SERVICE: "/create-service",
	VIEW_SERVICE: "/view-service",
	UPDATE_SERVICE: "/update-service",
	DELETE_SERVICE: "/delete-service",
	UPDATE_USER: "/update-user",
	GET_USER_ROLE: "/get-user-role",
	CREATE_VOUCHER: "/create-voucher",
	VIEW_VOUCHER: "/view-voucher",
	UPDATE_VOUCHER: "/update-voucher",
	DELETE_VOUCHER: "/delete-voucher",
	VIEW_STYLISTS: "/get-all-stylists",
	SCHEDULE_STYLISTS_APPOINTMENTS: "/available-time-slots",
	GET_APPOINTMENT_USER: "/get-appointment-user",
};
=======
	GET_PROFILE_USER: "/get-profile",
	UPDATE_PROFILE_USER: "/update-profile",
	CHANGE_PASSWORD: "/change-password",
	VIEW_BLOG: "/get-blog",
	VIEW_PRODUCT_SKINCARE: "/get-product-skincare",
	VIEW_QNA: "/get-qna",
	UPDATE_QNA: "/update-qna",
	DELETE_QNA: "/delete-qna",
	SEARCH_PRODUCT: "/search-product",
	FILTER_PRODUCT: "/filter-product",
	CHECKOUT: "/checkout",
	UPDATE_ORDER: "/update-order",
	CREATE_QUESTION: "/create-question",
	UPDATE_QUESTION: "/update-question",
	DELETE_QUESTION: "/delete-question",
	VIEW_FORM: "/get-form",
	UPDATE_FORM: "/update-form",
	DELETE_FORM: "/delete-form",
	CREATE_QUIZ: "/create-quiz",
	UPDATE_QUIZ: "/update-quiz",
	DELETE_QUIZ: "/delete-quiz",
};

>>>>>>> origin/master
export default endpoints;
