const endpoints = {
	LOGIN: "/login",
	REGISTER: "/register",
	SEND_OTP: "/send-otp",
	VERIFY_OTP_CHANGE_PASSWORD: "/verify-otp-and-change-password",
	GET_PROFILE_USER: "/get-profile",
	UPDATE_PROFILE_USER: "/update-profile",
	CHANGE_PASSWORD: "/change-password",
	VIEW_BLOG: "/get-blog",
	VIEW_PRODUCT_SKINCARE: "/get-product-skincare",
	VIEW_QNA: "/get-qna",
	UPDATE_QNA: "/update-qna",
	DELETE_QNA: "/delete-qna",
	SEARCH_PRODUCT: "/search-product",
	FILTER_PRODUCT: "/filter-product",
	CHECKOUT: "/checkout",
	UPDATE_ORDER: "/update-order",
	CREATE_QUESTION: "/create-question",
	UPDATE_QUESTION: "/update-question",
	DELETE_QUESTION: "/delete-question",
	VIEW_FORM: "/get-form",
	UPDATE_FORM: "/update-form",
	DELETE_FORM: "/delete-form",
	CREATE_QUIZ: "/create-quiz",
	UPDATE_QUIZ: "/update-quiz",
	DELETE_QUIZ: "/delete-quiz",
};

export default endpoints;
